import { Demanda } from '@/types/demandas';

export const mockDemandas: Demanda[] = [
  {
    id: '1',
    titulo: 'Configurar novo equipamento de som',
    descricao: 'Precisamos configurar e testar o novo sistema de som adquirido para eventos corporativos.',
    categoria: 'tecnica',
    prioridade: 'alta',
    status: 'em-andamento',
    solicitante: 'Rafael Mendes',
    solicitanteId: '1',
    responsavel: 'João Silva',
    responsavelId: 'user-1',
    dataCriacao: '2024-01-15T10:00:00',
    dataAtualizacao: '2024-01-16T14:30:00',
    prazo: '2024-01-20T18:00:00',
    comentarios: [
      {
        id: 'c1',
        autor: 'João Silva',
        autorId: 'user-1',
        conteudo: 'Já recebi o equipamento, vou iniciar os testes hoje à tarde.',
        dataHora: '2024-01-16T09:00:00',
      },
    ],
    anexos: [],
    tags: ['equipamento', 'som', 'urgente'],
  },
  {
    id: '2',
    titulo: 'Atualizar lista de fornecedores',
    descricao: 'Revisar e atualizar a lista de fornecedores homologados, incluindo novos contatos e removendo empresas inativas.',
    categoria: 'administrativa',
    prioridade: 'media',
    status: 'aberta',
    solicitante: 'Fernanda Oliveira',
    solicitanteId: '2',
    dataCriacao: '2024-01-18T11:30:00',
    dataAtualizacao: '2024-01-18T11:30:00',
    prazo: '2024-01-25T17:00:00',
    comentarios: [],
    anexos: [],
    tags: ['fornecedores', 'cadastro'],
  },
  {
    id: '3',
    titulo: 'Revisar proposta comercial - Cliente XYZ',
    descricao: 'Analisar e ajustar a proposta comercial para o evento corporativo do cliente XYZ com base no feedback recebido.',
    categoria: 'comercial',
    prioridade: 'urgente',
    status: 'aberta',
    solicitante: 'Lucas Barbosa',
    solicitanteId: '3',
    responsavel: 'Camila Rodrigues',
    responsavelId: '4',
    dataCriacao: '2024-01-19T08:00:00',
    dataAtualizacao: '2024-01-19T08:00:00',
    prazo: '2024-01-20T12:00:00',
    comentarios: [],
    anexos: [],
    eventoRelacionado: '1',
    tags: ['proposta', 'comercial', 'cliente'],
  },
  {
    id: '4',
    titulo: 'Manutenção preventiva de equipamentos',
    descricao: 'Realizar manutenção preventiva em todos os equipamentos de iluminação antes da alta temporada.',
    categoria: 'operacional',
    prioridade: 'media',
    status: 'concluida',
    solicitante: 'Pedro Souza',
    solicitanteId: '5',
    responsavel: 'João Silva',
    responsavelId: 'user-1',
    dataCriacao: '2024-01-10T14:00:00',
    dataAtualizacao: '2024-01-17T16:00:00',
    dataConclusao: '2024-01-17T16:00:00',
    prazo: '2024-01-18T18:00:00',
    comentarios: [
      {
        id: 'c2',
        autor: 'João Silva',
        autorId: 'user-1',
        conteudo: 'Manutenção concluída. Todos os equipamentos estão em perfeito estado.',
        dataHora: '2024-01-17T16:00:00',
      },
    ],
    anexos: [],
    tags: ['manutenção', 'equipamentos'],
  },
  {
    id: '5',
    titulo: 'Conciliação financeira do mês',
    descricao: 'Realizar a conciliação financeira de todas as contas do mês de dezembro.',
    categoria: 'financeira',
    prioridade: 'alta',
    status: 'em-andamento',
    solicitante: 'Fernanda Oliveira',
    solicitanteId: '2',
    responsavel: 'Camila Rodrigues',
    responsavelId: '4',
    dataCriacao: '2024-01-05T09:00:00',
    dataAtualizacao: '2024-01-15T10:30:00',
    prazo: '2024-01-22T17:00:00',
    comentarios: [],
    anexos: [],
    tags: ['financeiro', 'conciliação'],
  },
];

export const mockUsuarios = [
  { id: 'user-1', nome: 'João Silva' },
  { id: 'user-2', nome: 'Maria Santos' },
  { id: '1', nome: 'Rafael Mendes' },
  { id: '2', nome: 'Fernanda Oliveira' },
  { id: '3', nome: 'Lucas Barbosa' },
  { id: '4', nome: 'Camila Rodrigues' },
  { id: '5', nome: 'Pedro Souza' },
];
