import { Evento } from '@/types/eventos';
import { mockClientes } from './clientes';

const comerciais = [
  { id: '2', nome: 'Maria Santos', email: 'comercial@gestao.com' },
  { id: '4', nome: 'Pedro Oliveira', email: 'pedro@gestao.com' },
  { id: '5', nome: 'Ana Rodrigues', email: 'ana@gestao.com' },
];

export const mockEventos: Evento[] = [
  {
    id: '1',
    nome: 'Festa de Aniversário João - 50 Anos',
    dataInicio: '2025-10-15',
    dataFim: '2025-10-15',
    horaInicio: '19:00',
    horaFim: '23:00',
    local: 'Buffet Estrela Dourada',
    cidade: 'Cuiabá',
    estado: 'MT',
    endereco: 'Rua das Acácias, 890 - Quilombo',
    cliente: mockClientes[0],
    comercial: comerciais[0],
    status: 'confirmado',
    tipoEvento: 'bar',
    tags: ['Bar', 'Aniversário', 'Premium'],
    plantaBaixa: '/uploads/planta-evento-1.pdf',
    descricao: 'Festa de 50 anos com aproximadamente 150 convidados. Decoração clássica com tema azul e dourado.',
    observacoes: 'Cliente solicitou open bar premium e DJ profissional.',
    checklist: [
      { id: '1', itemId: 'item-1', nome: 'Mesa Redonda 1,5m', quantidade: 10, alocado: 10 },
      { id: '2', itemId: 'item-2', nome: 'Cadeira Branca', quantidade: 40, alocado: 40 },
      { id: '3', itemId: 'item-3', nome: 'Toalha de Mesa Azul', quantidade: 10, alocado: 8 },
      { id: '4', itemId: 'item-4', nome: 'Sistema de Som Completo', quantidade: 1, alocado: 1 },
      { id: '5', itemId: 'item-5', nome: 'Iluminação LED', quantidade: 20, alocado: 20 },
    ],
    materiaisAlocados: {
      antecipado: [
        {
          id: '1',
          itemId: 'mesa-001',
          nome: 'Mesa Redonda 1,5m',
          serial: 'MES-001',
          transportadora: 'TransLog',
          dataEnvio: '2025-10-12',
          rastreamento: 'BR123456789MT',
          status: 'separado',
        },
        {
          id: '2',
          itemId: 'cadeira-001',
          nome: 'Cadeira Branca',
          serial: 'CAD-001-040',
          transportadora: 'TransLog',
          dataEnvio: '2025-10-12',
          status: 'separado',
        },
      ],
      comTecnicos: [
        {
          id: '3',
          itemId: 'som-001',
          nome: 'Sistema de Som Completo',
          serial: 'SOM-PRO-001',
          responsavel: 'Carlos Silva',
          status: 'preparado',
        },
        {
          id: '4',
          itemId: 'luz-001',
          nome: 'Iluminação LED',
          serial: 'LED-SET-001',
          responsavel: 'Carlos Silva',
          status: 'preparado',
        },
      ],
    },
    financeiro: {
      receitas: [
        {
          id: '1',
          descricao: 'Contrato de Serviço - Pacote Premium',
          tipo: 'fixo',
          quantidade: 1,
          valorUnitario: 12500,
          valor: 12500,
          status: 'pago',
          data: '2025-09-20',
          comprovante: '/uploads/comprovante-1.pdf',
        },
        {
          id: '2',
          descricao: 'Taxa adicional de decoração',
          tipo: 'fixo',
          quantidade: 1,
          valorUnitario: 2500,
          valor: 2500,
          status: 'pendente',
          data: '2025-10-01',
        },
      ],
      despesas: [
        {
          id: '1',
          descricao: 'Mão de Obra - 4 Técnicos',
          categoria: 'pessoal',
          quantidade: 4,
          valorUnitario: 400,
          valor: 1600,
          data: '2025-10-15',
        },
        {
          id: '2',
          descricao: 'Transporte de Materiais',
          categoria: 'transporte',
          quantidade: 1,
          valorUnitario: 350,
          valor: 350,
          data: '2025-10-12',
        },
      ],
      cobrancas: [],
    },
    timeline: [
      {
        id: '1',
        data: '2025-09-20T10:30:00',
        tipo: 'criacao',
        usuario: 'Maria Santos',
        descricao: 'Evento criado',
      },
      {
        id: '2',
        data: '2025-09-22T14:15:00',
        tipo: 'confirmacao',
        usuario: 'Maria Santos',
        descricao: 'Evento confirmado pelo cliente',
      },
      {
        id: '3',
        data: '2025-10-05T09:00:00',
        tipo: 'alocacao',
        usuario: 'Carlos Silva',
        descricao: 'Materiais alocados',
      },
    ],
    equipe: [
      { id: '1', nome: 'Carlos Silva', funcao: 'Técnico Líder', telefone: '(65) 98888-7777' },
      { id: '2', nome: 'Paulo Santos', funcao: 'Técnico', telefone: '(65) 97777-6666' },
      { id: '3', nome: 'Rafael Costa', funcao: 'Técnico', telefone: '(65) 96666-5555' },
      { id: '4', nome: 'Lucas Mendes', funcao: 'Técnico', telefone: '(65) 95555-4444' },
    ],
    observacoesOperacionais: [
      'Montagem deve iniciar às 14h',
      'Cliente confirmou presença durante montagem',
      'Atenção especial com sistema de som - evento em local fechado',
    ],
    criadoEm: '2025-09-20T10:30:00',
    atualizadoEm: '2025-10-05T09:00:00',
  },
  {
    id: '2',
    nome: 'Casamento Ana & Pedro',
    dataInicio: '2025-11-20',
    dataFim: '2025-11-21',
    horaInicio: '18:00',
    horaFim: '02:00',
    local: 'Fazenda Vista Linda',
    cidade: 'Várzea Grande',
    estado: 'MT',
    endereco: 'Rodovia BR-364, Km 15',
    cliente: mockClientes[4],
    comercial: comerciais[0],
    status: 'materiais_alocados',
    tipoEvento: 'hibrido',
    tags: ['Casamento', 'Luxo', 'Fazenda'],
    plantaBaixa: '/uploads/planta-evento-2.pdf',
    descricao: 'Casamento ao ar livre com 200 convidados. Cerimônia ao pôr do sol seguida de festa.',
    checklist: [
      { id: '1', itemId: 'item-6', nome: 'Tenda 10x10m', quantidade: 2, alocado: 2 },
      { id: '2', itemId: 'item-7', nome: 'Mesa Retangular 2m', quantidade: 20, alocado: 20 },
      { id: '3', itemId: 'item-8', nome: 'Cadeira Tiffany', quantidade: 200, alocado: 200 },
      { id: '4', itemId: 'item-9', nome: 'Sistema de Som e Iluminação Completo', quantidade: 1, alocado: 1 },
      { id: '5', itemId: 'item-10', nome: 'Gerador de Energia 50kVA', quantidade: 1, alocado: 1 },
      { id: '6', itemId: 'item-11', nome: 'Pista de Dança LED', quantidade: 1, alocado: 1 },
    ],
    materiaisAlocados: {
      antecipado: [
        {
          id: '1',
          itemId: 'tenda-001',
          nome: 'Tenda 10x10m',
          serial: 'TND-001',
          transportadora: 'Transvale',
          dataEnvio: '2025-11-18',
          status: 'reservado',
        },
        {
          id: '2',
          itemId: 'tenda-002',
          nome: 'Tenda 10x10m',
          serial: 'TND-002',
          transportadora: 'Transvale',
          dataEnvio: '2025-11-18',
          status: 'reservado',
        },
      ],
      comTecnicos: [
        {
          id: '3',
          itemId: 'som-002',
          nome: 'Sistema de Som e Iluminação Completo',
          serial: 'SOM-LUX-001',
          responsavel: 'Carlos Silva',
          status: 'reservado',
        },
        {
          id: '4',
          itemId: 'gerador-001',
          nome: 'Gerador de Energia 50kVA',
          serial: 'GER-050-001',
          responsavel: 'Paulo Santos',
          status: 'reservado',
        },
      ],
    },
    financeiro: {
      receitas: [
        {
          id: '1',
          descricao: 'Contrato Casamento Completo',
          tipo: 'fixo',
          quantidade: 1,
          valorUnitario: 35000,
          valor: 35000,
          status: 'pendente',
          data: '2025-11-01',
        },
      ],
      despesas: [
        {
          id: '1',
          descricao: 'Equipe Técnica - 8 Profissionais',
          categoria: 'pessoal',
          quantidade: 8,
          valorUnitario: 500,
          valor: 4000,
          data: '2025-11-20',
        },
        {
          id: '2',
          descricao: 'Transporte Especial para Fazenda',
          categoria: 'transporte',
          quantidade: 1,
          valorUnitario: 1200,
          valor: 1200,
          data: '2025-11-18',
        },
      ],
      cobrancas: [],
    },
    timeline: [
      {
        id: '1',
        data: '2025-08-15T11:00:00',
        tipo: 'criacao',
        usuario: 'Maria Santos',
        descricao: 'Evento criado',
      },
      {
        id: '2',
        data: '2025-08-20T16:30:00',
        tipo: 'confirmacao',
        usuario: 'Maria Santos',
        descricao: 'Contrato assinado',
      },
      {
        id: '3',
        data: '2025-10-10T10:00:00',
        tipo: 'alocacao',
        usuario: 'Carlos Silva',
        descricao: 'Materiais separados',
      },
    ],
    equipe: [
      { id: '1', nome: 'Carlos Silva', funcao: 'Coordenador', telefone: '(65) 98888-7777' },
      { id: '2', nome: 'Paulo Santos', funcao: 'Técnico Elétrica', telefone: '(65) 97777-6666' },
    ],
    observacoesOperacionais: [
      'Montagem inicia às 10h do dia 19/11',
      'Local sem energia elétrica - gerador obrigatório',
      'Acesso por estrada de terra - verificar condições climáticas',
    ],
    criadoEm: '2025-08-15T11:00:00',
    atualizadoEm: '2025-10-10T10:00:00',
  },
  {
    id: '3',
    nome: 'Evento Corporativo - Lançamento Produto XYZ',
    dataInicio: '2025-10-25',
    dataFim: '2025-10-25',
    horaInicio: '19:30',
    horaFim: '22:30',
    local: 'Centro de Convenções Pantanal',
    cidade: 'Cuiabá',
    estado: 'MT',
    endereco: 'Av. Historiador Rubens de Mendonça, 5000',
    cliente: mockClientes[9],
    comercial: comerciais[1],
    status: 'em_preparacao',
    tipoEvento: 'ingresso',
    tags: ['Corporativo', 'Lançamento', 'Tech'],
    descricao: 'Evento de lançamento de produto com coquetel e apresentações.',
    checklist: [
      { id: '1', itemId: 'item-12', nome: 'Palco Modular 6x4m', quantidade: 1, alocado: 1 },
      { id: '2', itemId: 'item-13', nome: 'Telão LED 4x3m', quantidade: 1, alocado: 1 },
      { id: '3', itemId: 'item-14', nome: 'Sistema de Som Profissional', quantidade: 1, alocado: 1 },
      { id: '4', itemId: 'item-15', nome: 'Mesa Lounge', quantidade: 15, alocado: 15 },
      { id: '5', itemId: 'item-16', nome: 'Sofá Lounge', quantidade: 10, alocado: 10 },
    ],
    materiaisAlocados: {
      antecipado: [],
      comTecnicos: [
        {
          id: '1',
          itemId: 'palco-001',
          nome: 'Palco Modular 6x4m',
          serial: 'PAL-MOD-001',
          responsavel: 'Carlos Silva',
          status: 'preparado',
        },
        {
          id: '2',
          itemId: 'telao-001',
          nome: 'Telão LED 4x3m',
          serial: 'LED-SCR-001',
          responsavel: 'Paulo Santos',
          status: 'preparado',
        },
      ],
    },
    financeiro: {
      receitas: [
        {
          id: '1',
          descricao: 'Pacote Corporativo Premium',
          tipo: 'fixo',
          quantidade: 1,
          valorUnitario: 28000,
          valor: 28000,
          status: 'pago',
          data: '2025-09-25',
        },
      ],
      despesas: [
        {
          id: '1',
          descricao: 'Equipe Montagem',
          categoria: 'pessoal',
          quantidade: 6,
          valorUnitario: 450,
          valor: 2700,
          data: '2025-10-25',
        },
      ],
      cobrancas: [],
    },
    timeline: [
      {
        id: '1',
        data: '2025-09-10T09:00:00',
        tipo: 'criacao',
        usuario: 'Pedro Oliveira',
        descricao: 'Evento criado',
      },
      {
        id: '2',
        data: '2025-09-12T14:00:00',
        tipo: 'confirmacao',
        usuario: 'Pedro Oliveira',
        descricao: 'Proposta aprovada',
      },
    ],
    equipe: [
      { id: '1', nome: 'Carlos Silva', funcao: 'Coordenador Técnico', telefone: '(65) 98888-7777' },
    ],
    observacoesOperacionais: ['Montagem dia 25/10 às 14h', 'Cliente exige sigilo total'],
    criadoEm: '2025-09-10T09:00:00',
    atualizadoEm: '2025-10-08T11:20:00',
  },
  {
    id: '4',
    nome: 'Formatura Medicina UFMT 2025',
    dataInicio: '2025-12-15',
    dataFim: '2025-12-16',
    horaInicio: '20:00',
    horaFim: '04:00',
    local: 'Grand Hall Eventos',
    cidade: 'Cuiabá',
    estado: 'MT',
    endereco: 'Av. Miguel Sutil, 8000',
    cliente: mockClientes[6],
    comercial: comerciais[2],
    status: 'orcamento_enviado',
    tipoEvento: 'hibrido',
    tags: ['Formatura', 'Acadêmico'],
    checklist: [],
    materiaisAlocados: {
      antecipado: [],
      comTecnicos: [],
    },
    financeiro: {
      receitas: [],
      despesas: [],
      cobrancas: [],
    },
    timeline: [
      {
        id: '1',
        data: '2025-10-05T10:00:00',
        tipo: 'criacao',
        usuario: 'Ana Rodrigues',
        descricao: 'Orçamento solicitado',
      },
    ],
    equipe: [],
    observacoesOperacionais: [],
    criadoEm: '2025-10-05T10:00:00',
    atualizadoEm: '2025-10-05T10:00:00',
  },
  {
    id: '5',
    nome: 'Show Ao Vivo - Banda XYZ',
    dataInicio: '2025-11-05',
    dataFim: '2025-11-06',
    horaInicio: '21:00',
    horaFim: '01:00',
    local: 'Arena Pantanal',
    cidade: 'Cuiabá',
    estado: 'MT',
    endereco: 'Av. Agrícola Paes de Barros',
    cliente: mockClientes[1],
    comercial: comerciais[0],
    status: 'aguardando_alocacao',
    tipoEvento: 'ingresso',
    tags: ['Show', 'Música', 'Grande Porte'],
    descricao: 'Show para 5000 pessoas com estrutura completa de palco e som.',
    checklist: [
      { id: '1', itemId: 'item-17', nome: 'Palco Estrutura Grande 12x8m', quantidade: 1, alocado: 0 },
      { id: '2', itemId: 'item-18', nome: 'Line Array Completo', quantidade: 1, alocado: 0 },
      { id: '3', itemId: 'item-19', nome: 'Mesa de Som Digital 48 Canais', quantidade: 1, alocado: 0 },
      { id: '4', itemId: 'item-20', nome: 'Iluminação Robotizada', quantidade: 30, alocado: 0 },
      { id: '5', itemId: 'item-21', nome: 'Gerador 100kVA', quantidade: 2, alocado: 0 },
    ],
    materiaisAlocados: {
      antecipado: [],
      comTecnicos: [],
    },
    financeiro: {
      receitas: [
        {
          id: '1',
          descricao: 'Contrato Show - Estrutura Completa',
          tipo: 'fixo',
          quantidade: 1,
          valorUnitario: 85000,
          valor: 85000,
          status: 'pendente',
          data: '2025-10-20',
        },
      ],
      despesas: [],
      cobrancas: [],
    },
    timeline: [
      {
        id: '1',
        data: '2025-09-01T15:00:00',
        tipo: 'criacao',
        usuario: 'Maria Santos',
        descricao: 'Evento criado',
      },
      {
        id: '2',
        data: '2025-09-15T11:00:00',
        tipo: 'confirmacao',
        usuario: 'Maria Santos',
        descricao: 'Contrato assinado',
      },
    ],
    equipe: [],
    observacoesOperacionais: ['Montagem 3 dias antes', 'Necessário equipe mínima de 15 técnicos'],
    criadoEm: '2025-09-01T15:00:00',
    atualizadoEm: '2025-09-15T11:00:00',
  },
];
