import { Transportadora, Envio } from '@/types/transportadoras';

export const transportadorasMock: Transportadora[] = [
  {
    id: '1',
    nome: 'Transportadora Rápida',
    cnpj: '12.345.678/0001-90',
    razaoSocial: 'Transportadora Rápida Ltda',
    telefone: '(11) 3456-7890',
    email: 'contato@transportadorarapida.com.br',
    responsavel: 'João Silva',
    status: 'ativa',
    endereco: {
      cep: '01310-100',
      rua: 'Av. Paulista',
      numero: '1000',
      bairro: 'Bela Vista',
      cidade: 'São Paulo',
      estado: 'SP',
    },
    dadosBancarios: {
      banco: 'Banco do Brasil',
      agencia: '1234-5',
      conta: '12345-6',
      tipoConta: 'corrente',
    },
    rotasAtendidas: [
      {
        id: '1',
        cidadeDestino: 'Rio de Janeiro',
        estadoDestino: 'RJ',
        prazoEntrega: 2,
        valorBase: 2500,
        ativa: true,
      },
      {
        id: '2',
        cidadeDestino: 'Belo Horizonte',
        estadoDestino: 'MG',
        prazoEntrega: 1,
        valorBase: 1800,
        ativa: true,
      },
      {
        id: '3',
        cidadeDestino: 'Curitiba',
        estadoDestino: 'PR',
        prazoEntrega: 1,
        valorBase: 1500,
        ativa: true,
      },
    ],
    criadoEm: '2024-01-15T10:00:00',
    atualizadoEm: '2024-01-15T10:00:00',
  },
  {
    id: '2',
    nome: 'LogTrans Logística',
    cnpj: '23.456.789/0001-01',
    razaoSocial: 'LogTrans Logística e Transportes S.A.',
    telefone: '(21) 2345-6789',
    email: 'comercial@logtrans.com.br',
    responsavel: 'Maria Santos',
    status: 'ativa',
    endereco: {
      cep: '20040-020',
      rua: 'Av. Rio Branco',
      numero: '500',
      bairro: 'Centro',
      cidade: 'Rio de Janeiro',
      estado: 'RJ',
    },
    rotasAtendidas: [
      {
        id: '1',
        cidadeDestino: 'Salvador',
        estadoDestino: 'BA',
        prazoEntrega: 3,
        valorBase: 3200,
        ativa: true,
      },
      {
        id: '2',
        cidadeDestino: 'São Paulo',
        estadoDestino: 'SP',
        prazoEntrega: 1,
        valorBase: 2000,
        ativa: true,
      },
      {
        id: '3',
        cidadeDestino: 'Brasília',
        estadoDestino: 'DF',
        prazoEntrega: 2,
        valorBase: 2800,
        ativa: true,
      },
    ],
    criadoEm: '2024-02-10T14:30:00',
    atualizadoEm: '2024-02-10T14:30:00',
  },
];

export const enviosMock: Envio[] = [
  {
    id: '1',
    transportadoraId: '1',
    eventoId: '1',
    tipo: 'ida',
    status: 'entregue',
    dataColeta: '2024-03-01T08:00:00',
    dataEntrega: '2024-03-02T16:00:00',
    dataEntregaPrevista: '2024-03-02T18:00:00',
    origem: 'São Paulo - SP',
    destino: 'Belo Horizonte - MG',
    rastreio: 'TR123456789BR',
    valor: 2500,
    formaPagamento: 'antecipado',
    criadoEm: '2024-02-28T10:00:00',
    atualizadoEm: '2024-03-02T16:30:00',
  },
  {
    id: '2',
    transportadoraId: '2',
    eventoId: '2',
    tipo: 'ida',
    status: 'em_transito',
    dataColeta: '2024-03-10T09:00:00',
    dataEntregaPrevista: '2024-03-12T14:00:00',
    origem: 'Rio de Janeiro - RJ',
    destino: 'Salvador - BA',
    rastreio: 'LT987654321BR',
    valor: 3200,
    formaPagamento: 'na_entrega',
    observacoes: 'Material frágil - cuidado no transporte',
    criadoEm: '2024-03-08T11:00:00',
    atualizadoEm: '2024-03-10T09:15:00',
  },
];
